/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_YY_PARSER_H_INCLUDED
# define YY_YY_PARSER_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    TOKEN_EOF = 0,                 /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    THREEDIMENSIONAL = 258,        /* "3D"  */
    ABSENT = 259,                  /* ABSENT  */
    ACCEPT = 260,                  /* ACCEPT  */
    ACCESS = 261,                  /* ACCESS  */
    ACTIVEX = 262,                 /* "ACTIVE-X"  */
    ACTIVE_CLASS = 263,            /* "ACTIVE-CLASS"  */
    ACTION = 264,                  /* ACTION  */
    ACTUAL = 265,                  /* ACTUAL  */
    ADD = 266,                     /* ADD  */
    ADDRESS = 267,                 /* ADDRESS  */
    ADJUSTABLE_COLUMNS = 268,      /* "ADJUSTABLE-COLUMNS"  */
    ADVANCING = 269,               /* ADVANCING  */
    AFTER = 270,                   /* AFTER  */
    ALIGNED = 271,                 /* ALIGNED  */
    ALIGNMENT = 272,               /* ALIGNMENT  */
    ALL = 273,                     /* ALL  */
    ALLOCATE = 274,                /* ALLOCATE  */
    ALLOWING = 275,                /* ALLOWING  */
    ALPHABET = 276,                /* ALPHABET  */
    ALPHABETIC = 277,              /* ALPHABETIC  */
    ALPHABETIC_LOWER = 278,        /* "ALPHABETIC-LOWER"  */
    ALPHABETIC_UPPER = 279,        /* "ALPHABETIC-UPPER"  */
    ALPHANUMERIC = 280,            /* ALPHANUMERIC  */
    ALPHANUMERIC_EDITED = 281,     /* "ALPHANUMERIC-EDITED"  */
    ALSO = 282,                    /* ALSO  */
    ALTER = 283,                   /* ALTER  */
    ALTERNATE = 284,               /* ALTERNATE  */
    AND = 285,                     /* AND  */
    ANY = 286,                     /* ANY  */
    APPLY = 287,                   /* APPLY  */
    ARE = 288,                     /* ARE  */
    AREA = 289,                    /* AREA  */
    AREAS = 290,                   /* AREAS  */
    ARGUMENT_NUMBER = 291,         /* "ARGUMENT-NUMBER"  */
    ARGUMENT_VALUE = 292,          /* "ARGUMENT-VALUE"  */
    ARITHMETIC = 293,              /* ARITHMETIC  */
    AS = 294,                      /* AS  */
    ASCENDING = 295,               /* ASCENDING  */
    ASCII = 296,                   /* ASCII  */
    ASSIGN = 297,                  /* ASSIGN  */
    AT = 298,                      /* AT  */
    AT_END = 299,                  /* "AT END"  */
    ATTRIBUTE = 300,               /* ATTRIBUTE  */
    ATTRIBUTES = 301,              /* ATTRIBUTES  */
    AUTHOR = 302,                  /* AUTHOR  */
    AUTO = 303,                    /* AUTO  */
    AUTO_DECIMAL = 304,            /* "AUTO-DECIMAL"  */
    AUTO_SPIN = 305,               /* "AUTO-SPIN"  */
    AUTOMATIC = 306,               /* AUTOMATIC  */
    AWAY_FROM_ZERO = 307,          /* "AWAY-FROM-ZERO"  */
    B_AND = 308,                   /* "B-AND"  */
    B_NOT = 309,                   /* "B-NOT"  */
    B_OR = 310,                    /* "B-OR"  */
    B_XOR = 311,                   /* "B-XOR"  */
    B_SHIFT_L = 312,               /* "B-SHIFT-L"  */
    B_SHIFT_R = 313,               /* "B-SHIFT-R"  */
    B_SHIFT_LC = 314,              /* "B-SHIFT-LC"  */
    B_SHIFT_RC = 315,              /* "B-SHIFT-RC"  */
    BACKGROUND_COLOR = 316,        /* "BACKGROUND-COLOR"  */
    BACKGROUND_HIGH = 317,         /* "BACKGROUND-HIGH"  */
    BACKGROUND_LOW = 318,          /* "BACKGROUND-LOW"  */
    BACKGROUND_STANDARD = 319,     /* "BACKGROUND-STANDARD"  */
    BACKWARD = 320,                /* BACKWARD  */
    BAR = 321,                     /* BAR  */
    BASED = 322,                   /* BASED  */
    BEFORE = 323,                  /* BEFORE  */
    BELL = 324,                    /* BELL  */
    BINARY = 325,                  /* BINARY  */
    BINARY_C_LONG = 326,           /* "BINARY-C-LONG"  */
    BINARY_CHAR = 327,             /* "BINARY-CHAR"  */
    BINARY_DOUBLE = 328,           /* "BINARY-DOUBLE"  */
    BINARY_LONG = 329,             /* "BINARY-LONG"  */
    BINARY_SEQUENTIAL = 330,       /* "BINARY-SEQUENTIAL"  */
    BINARY_SHORT = 331,            /* "BINARY-SHORT"  */
    BIT = 332,                     /* BIT  */
    BITMAP = 333,                  /* BITMAP  */
    BITMAP_END = 334,              /* "BITMAP-END"  */
    BITMAP_HANDLE = 335,           /* "BITMAP-HANDLE"  */
    BITMAP_NUMBER = 336,           /* "BITMAP-NUMBER"  */
    BITMAP_START = 337,            /* "BITMAP-START"  */
    BITMAP_TIMER = 338,            /* "BITMAP-TIMER"  */
    BITMAP_TRAILING = 339,         /* "BITMAP-TRAILING"  */
    BITMAP_TRANSPARENT_COLOR = 340, /* "BITMAP-TRANSPARENT-COLOR"  */
    BITMAP_WIDTH = 341,            /* "BITMAP-WIDTH"  */
    BLANK = 342,                   /* BLANK  */
    BLINK = 343,                   /* BLINK  */
    BLOCK = 344,                   /* BLOCK  */
    BOOLEAN = 345,                 /* BOOLEAN  */
    BOTTOM = 346,                  /* BOTTOM  */
    BOX = 347,                     /* BOX  */
    BOXED = 348,                   /* BOXED  */
    BULK_ADDITION = 349,           /* "BULK-ADDITION"  */
    BUSY = 350,                    /* BUSY  */
    BUTTONS = 351,                 /* BUTTONS  */
    BY = 352,                      /* BY  */
    BYTE_LENGTH = 353,             /* "BYTE-LENGTH"  */
    C = 354,                       /* C  */
    CALENDAR_FONT = 355,           /* "CALENDAR-FONT"  */
    CALL = 356,                    /* CALL  */
    CANCEL = 357,                  /* CANCEL  */
    CANCEL_BUTTON = 358,           /* "CANCEL-BUTTON"  */
    CAPACITY = 359,                /* CAPACITY  */
    CARD_PUNCH = 360,              /* "CARD-PUNCH"  */
    CARD_READER = 361,             /* "CARD-READER"  */
    CASSETTE = 362,                /* CASSETTE  */
    CCOL = 363,                    /* CCOL  */
    CD = 364,                      /* CD  */
    CELL = 365,                    /* CELL  */
    CELL_COLOR = 366,              /* "CELL-COLOR"  */
    CELL_DATA = 367,               /* "CELL-DATA"  */
    CELL_FONT = 368,               /* "CELL-FONT"  */
    CELL_PROTECTION = 369,         /* "CELL-PROTECTION"  */
    CENTER = 370,                  /* CENTER  */
    CENTERED = 371,                /* CENTERED  */
    CENTERED_HEADINGS = 372,       /* "CENTERED-HEADINGS"  */
    CENTURY_DATE = 373,            /* "CENTURY-DATE"  */
    CF = 374,                      /* CF  */
    CH = 375,                      /* CH  */
    CHAINING = 376,                /* CHAINING  */
    CHANGED = 377,                 /* CHANGED  */
    CHARACTER = 378,               /* CHARACTER  */
    CHARACTERS = 379,              /* CHARACTERS  */
    CHECK_BOX = 380,               /* "CHECK-BOX"  */
    CLASS = 381,                   /* CLASS  */
    CLASSIFICATION = 382,          /* CLASSIFICATION  */
    CLASS_NAME = 383,              /* "class-name"  */
    CLEAR_SELECTION = 384,         /* "CLEAR-SELECTION"  */
    CLINE = 385,                   /* CLINE  */
    CLINES = 386,                  /* CLINES  */
    CLOSE = 387,                   /* CLOSE  */
    COBOL = 388,                   /* COBOL  */
    CODE = 389,                    /* CODE  */
    CODE_SET = 390,                /* "CODE-SET"  */
    COLLATING = 391,               /* COLLATING  */
    COL = 392,                     /* COL  */
    COLOR = 393,                   /* COLOR  */
    COLORS = 394,                  /* COLORS  */
    COLS = 395,                    /* COLS  */
    COLUMN = 396,                  /* COLUMN  */
    COLUMN_COLOR = 397,            /* "COLUMN-COLOR"  */
    COLUMN_DIVIDERS = 398,         /* "COLUMN-DIVIDERS"  */
    COLUMN_FONT = 399,             /* "COLUMN-FONT"  */
    COLUMN_HEADINGS = 400,         /* "COLUMN-HEADINGS"  */
    COLUMN_PROTECTION = 401,       /* "COLUMN-PROTECTION"  */
    COLUMNS = 402,                 /* COLUMNS  */
    COMBO_BOX = 403,               /* "COMBO-BOX"  */
    COMMA = 404,                   /* COMMA  */
    COMMAND_LINE = 405,            /* "COMMAND-LINE"  */
    COMMA_DELIM = 406,             /* "comma delimiter"  */
    COMMIT = 407,                  /* COMMIT  */
    COMMON = 408,                  /* COMMON  */
    COMMUNICATION = 409,           /* COMMUNICATION  */
    COMP = 410,                    /* COMP  */
    COMPUTE = 411,                 /* COMPUTE  */
    COMP_0 = 412,                  /* "COMP-0"  */
    COMP_1 = 413,                  /* "COMP-1"  */
    COMP_2 = 414,                  /* "COMP-2"  */
    COMP_3 = 415,                  /* "COMP-3"  */
    COMP_4 = 416,                  /* "COMP-4"  */
    COMP_5 = 417,                  /* "COMP-5"  */
    COMP_6 = 418,                  /* "COMP-6"  */
    COMP_N = 419,                  /* "COMP-N"  */
    COMP_X = 420,                  /* "COMP-X"  */
    CONCATENATE_FUNC = 421,        /* "FUNCTION CONCATENATE"  */
    CONDITION = 422,               /* CONDITION  */
    CONFIGURATION = 423,           /* CONFIGURATION  */
    CONSTANT = 424,                /* CONSTANT  */
    CONTAINS = 425,                /* CONTAINS  */
    CONTENT = 426,                 /* CONTENT  */
    CONTENT_LENGTH_FUNC = 427,     /* "FUNCTION CONTENT-LENGTH"  */
    CONTENT_OF_FUNC = 428,         /* "FUNCTION CONTENT-OF"  */
    CONTINUE = 429,                /* CONTINUE  */
    CONTROL = 430,                 /* CONTROL  */
    CONTROLS = 431,                /* CONTROLS  */
    CONVERSION = 432,              /* CONVERSION  */
    CONVERTING = 433,              /* CONVERTING  */
    COPY = 434,                    /* COPY  */
    COPY_SELECTION = 435,          /* "COPY-SELECTION"  */
    CORE_INDEX = 436,              /* "CORE-INDEX"  */
    CORRESPONDING = 437,           /* CORRESPONDING  */
    COUNT = 438,                   /* COUNT  */
    CRT = 439,                     /* CRT  */
    CRT_UNDER = 440,               /* "CRT-UNDER"  */
    CSIZE = 441,                   /* CSIZE  */
    CURRENCY = 442,                /* CURRENCY  */
    CURRENT_DATE_FUNC = 443,       /* "FUNCTION CURRENT-DATE"  */
    CURSOR = 444,                  /* CURSOR  */
    CURSOR_COL = 445,              /* "CURSOR-COL"  */
    CURSOR_COLOR = 446,            /* "CURSOR-COLOR"  */
    CURSOR_FRAME_WIDTH = 447,      /* "CURSOR-FRAME-WIDTH"  */
    CURSOR_ROW = 448,              /* "CURSOR-ROW"  */
    CURSOR_X = 449,                /* "CURSOR-X"  */
    CURSOR_Y = 450,                /* "CURSOR-Y"  */
    CUSTOM_PRINT_TEMPLATE = 451,   /* "CUSTOM-PRINT-TEMPLATE"  */
    CYCLE = 452,                   /* CYCLE  */
    CYL_INDEX = 453,               /* "CYL-INDEX"  */
    CYL_OVERFLOW = 454,            /* "CYL-OVERFLOW"  */
    DASHED = 455,                  /* DASHED  */
    DATA = 456,                    /* DATA  */
    DATA_COLUMNS = 457,            /* "DATA-COLUMNS"  */
    DATA_POINTER = 458,            /* "DATA-POINTER"  */
    DATA_TYPES = 459,              /* "DATA-TYPES"  */
    DATE = 460,                    /* DATE  */
    DATE_COMPILED = 461,           /* "DATE-COMPILED"  */
    DATE_ENTRY = 462,              /* "DATE-ENTRY"  */
    DATE_MODIFIED = 463,           /* "DATE-MODIFIED"  */
    DATE_WRITTEN = 464,            /* "DATE-WRITTEN"  */
    DAY = 465,                     /* DAY  */
    DAY_OF_WEEK = 466,             /* "DAY-OF-WEEK"  */
    DE = 467,                      /* DE  */
    DEBUGGING = 468,               /* DEBUGGING  */
    DECIMAL_POINT = 469,           /* "DECIMAL-POINT"  */
    DECLARATIVES = 470,            /* DECLARATIVES  */
    DEFAULT = 471,                 /* DEFAULT  */
    DEFAULT_BUTTON = 472,          /* "DEFAULT-BUTTON"  */
    DEFAULT_FONT = 473,            /* "DEFAULT-FONT"  */
    DELETE = 474,                  /* DELETE  */
    DELIMITED = 475,               /* DELIMITED  */
    DELIMITER = 476,               /* DELIMITER  */
    DEPENDING = 477,               /* DEPENDING  */
    DESCENDING = 478,              /* DESCENDING  */
    DESTINATION = 479,             /* DESTINATION  */
    DESTROY = 480,                 /* DESTROY  */
    DETAIL = 481,                  /* DETAIL  */
    DISABLE = 482,                 /* DISABLE  */
    DISC = 483,                    /* DISC  */
    DISK = 484,                    /* DISK  */
    DISP = 485,                    /* DISP  */
    DISPLAY = 486,                 /* DISPLAY  */
    DISPLAY_1 = 487,               /* "DISPLAY-1"  */
    DISPLAY_COLUMNS = 488,         /* "DISPLAY-COLUMNS"  */
    DISPLAY_FORMAT = 489,          /* "DISPLAY-FORMAT"  */
    DISPLAY_OF_FUNC = 490,         /* "FUNCTION DISPLAY-OF"  */
    DIVIDE = 491,                  /* DIVIDE  */
    DIVIDERS = 492,                /* DIVIDERS  */
    DIVIDER_COLOR = 493,           /* "DIVIDER-COLOR"  */
    DIVISION = 494,                /* DIVISION  */
    DOTDASH = 495,                 /* DOTDASH  */
    DOTTED = 496,                  /* DOTTED  */
    DRAG_COLOR = 497,              /* "DRAG-COLOR"  */
    DROP_DOWN = 498,               /* "DROP-DOWN"  */
    DROP_LIST = 499,               /* "DROP-LIST"  */
    DOWN = 500,                    /* DOWN  */
    DUPLICATES = 501,              /* DUPLICATES  */
    DYNAMIC = 502,                 /* DYNAMIC  */
    EBCDIC = 503,                  /* EBCDIC  */
    EC = 504,                      /* EC  */
    ECHO = 505,                    /* ECHO  */
    EGI = 506,                     /* EGI  */
    EIGHTY_EIGHT = 507,            /* "level-number 88"  */
    ENABLE = 508,                  /* ENABLE  */
    ELEMENT = 509,                 /* ELEMENT  */
    ELSE = 510,                    /* ELSE  */
    EMI = 511,                     /* EMI  */
    ENCRYPTION = 512,              /* ENCRYPTION  */
    ENCODING = 513,                /* ENCODING  */
    END = 514,                     /* END  */
    END_ACCEPT = 515,              /* "END-ACCEPT"  */
    END_ADD = 516,                 /* "END-ADD"  */
    END_CALL = 517,                /* "END-CALL"  */
    END_COMPUTE = 518,             /* "END-COMPUTE"  */
    END_COLOR = 519,               /* "END-COLOR"  */
    END_DELETE = 520,              /* "END-DELETE"  */
    END_DISPLAY = 521,             /* "END-DISPLAY"  */
    END_DIVIDE = 522,              /* "END-DIVIDE"  */
    END_EVALUATE = 523,            /* "END-EVALUATE"  */
    END_FUNCTION = 524,            /* "END FUNCTION"  */
    END_IF = 525,                  /* "END-IF"  */
    END_JSON = 526,                /* "END-JSON"  */
    END_MODIFY = 527,              /* "END-MODIFY"  */
    END_MULTIPLY = 528,            /* "END-MULTIPLY"  */
    END_PERFORM = 529,             /* "END-PERFORM"  */
    END_PROGRAM = 530,             /* "END PROGRAM"  */
    END_READ = 531,                /* "END-READ"  */
    END_RECEIVE = 532,             /* "END-RECEIVE"  */
    END_RETURN = 533,              /* "END-RETURN"  */
    END_REWRITE = 534,             /* "END-REWRITE"  */
    END_SEARCH = 535,              /* "END-SEARCH"  */
    END_SEND = 536,                /* "END-SEND"  */
    END_START = 537,               /* "END-START"  */
    END_STRING = 538,              /* "END-STRING"  */
    END_SUBTRACT = 539,            /* "END-SUBTRACT"  */
    END_UNSTRING = 540,            /* "END-UNSTRING"  */
    END_WRITE = 541,               /* "END-WRITE"  */
    END_XML = 542,                 /* "END-XML"  */
    ENGRAVED = 543,                /* ENGRAVED  */
    ENSURE_VISIBLE = 544,          /* "ENSURE-VISIBLE"  */
    ENTRY = 545,                   /* ENTRY  */
    ENTRY_CONVENTION = 546,        /* "ENTRY-CONVENTION"  */
    ENTRY_FIELD = 547,             /* "ENTRY-FIELD"  */
    ENTRY_REASON = 548,            /* "ENTRY-REASON"  */
    ENVIRONMENT = 549,             /* ENVIRONMENT  */
    ENVIRONMENT_NAME = 550,        /* "ENVIRONMENT-NAME"  */
    ENVIRONMENT_VALUE = 551,       /* "ENVIRONMENT-VALUE"  */
    EOL = 552,                     /* EOL  */
    EOP = 553,                     /* EOP  */
    EOS = 554,                     /* EOS  */
    EQUAL = 555,                   /* EQUAL  */
    ERASE = 556,                   /* ERASE  */
    ERROR = 557,                   /* ERROR  */
    ESCAPE = 558,                  /* ESCAPE  */
    ESCAPE_BUTTON = 559,           /* "ESCAPE-BUTTON"  */
    ESI = 560,                     /* ESI  */
    EVALUATE = 561,                /* EVALUATE  */
    EVENT = 562,                   /* EVENT  */
    EVENT_LIST = 563,              /* "EVENT-LIST"  */
    EVENT_STATUS = 564,            /* "EVENT STATUS"  */
    EVERY = 565,                   /* EVERY  */
    EXAMINE = 566,                 /* EXAMINE  */
    EXCEPTION = 567,               /* EXCEPTION  */
    EXCEPTION_CONDITION = 568,     /* "EXCEPTION CONDITION"  */
    EXCEPTION_VALUE = 569,         /* "EXCEPTION-VALUE"  */
    EXPAND = 570,                  /* EXPAND  */
    EXCLUSIVE = 571,               /* EXCLUSIVE  */
    EXHIBIT = 572,                 /* EXHIBIT  */
    EXIT = 573,                    /* EXIT  */
    EXPONENTIATION = 574,          /* "exponentiation operator"  */
    EXTEND = 575,                  /* EXTEND  */
    EXTENDED_SEARCH = 576,         /* "EXTENDED-SEARCH"  */
    EXTERNAL = 577,                /* EXTERNAL  */
    EXTERNAL_FORM = 578,           /* "EXTERNAL-FORM"  */
    F = 579,                       /* F  */
    FACTORY = 580,                 /* FACTORY  */
    FD = 581,                      /* FD  */
    FH__FCD = 582,                 /* "FH--FCD"  */
    FH__KEYDEF = 583,              /* "FH--KEYDEF"  */
    FILE_CONTROL = 584,            /* "FILE-CONTROL"  */
    FILE_ID = 585,                 /* "FILE-ID"  */
    FILE_LIMIT = 586,              /* "FILE-LIMIT"  */
    FILE_LIMITS = 587,             /* "FILE-LIMITS"  */
    FILE_NAME = 588,               /* "FILE-NAME"  */
    FILE_POS = 589,                /* "FILE-POS"  */
    FILL_COLOR = 590,              /* "FILL-COLOR"  */
    FILL_COLOR2 = 591,             /* "FILL-COLOR2"  */
    FILL_PERCENT = 592,            /* "FILL-PERCENT"  */
    FILLER = 593,                  /* FILLER  */
    FINAL = 594,                   /* FINAL  */
    FINISH_REASON = 595,           /* "FINISH-REASON"  */
    FIRST = 596,                   /* FIRST  */
    FIXED = 597,                   /* FIXED  */
    FIXED_FONT = 598,              /* "FIXED-FONT"  */
    FIXED_WIDTH = 599,             /* "FIXED-WIDTH"  */
    FLAT = 600,                    /* FLAT  */
    FLAT_BUTTONS = 601,            /* "FLAT-BUTTONS"  */
    FLOAT_BINARY_128 = 602,        /* "FLOAT-BINARY-128"  */
    FLOAT_BINARY_32 = 603,         /* "FLOAT-BINARY-32"  */
    FLOAT_BINARY_64 = 604,         /* "FLOAT-BINARY-64"  */
    FLOAT_DECIMAL_16 = 605,        /* "FLOAT-DECIMAL-16"  */
    FLOAT_DECIMAL_34 = 606,        /* "FLOAT-DECIMAL-34"  */
    FLOAT_DECIMAL_7 = 607,         /* "FLOAT-DECIMAL-7"  */
    FLOAT_EXTENDED = 608,          /* "FLOAT-EXTENDED"  */
    FLOAT_LONG = 609,              /* "FLOAT-LONG"  */
    FLOAT_SHORT = 610,             /* "FLOAT-SHORT"  */
    FLOATING = 611,                /* FLOATING  */
    FONT = 612,                    /* FONT  */
    FOOTING = 613,                 /* FOOTING  */
    FOR = 614,                     /* FOR  */
    FOREGROUND_COLOR = 615,        /* "FOREGROUND-COLOR"  */
    FOREVER = 616,                 /* FOREVER  */
    FORMAT = 617,                  /* FORMAT  */
    FORMATTED_DATE_FUNC = 618,     /* "FUNCTION FORMATTED-DATE"  */
    FORMATTED_DATETIME_FUNC = 619, /* "FUNCTION FORMATTED-DATETIME"  */
    FORMATTED_TIME_FUNC = 620,     /* "FUNCTION FORMATTED-TIME"  */
    FRAME = 621,                   /* FRAME  */
    FRAMED = 622,                  /* FRAMED  */
    FREE = 623,                    /* FREE  */
    FROM = 624,                    /* FROM  */
    FROM_CRT = 625,                /* "FROM CRT"  */
    FULL = 626,                    /* FULL  */
    FULL_HEIGHT = 627,             /* "FULL-HEIGHT"  */
    FUNCTION = 628,                /* FUNCTION  */
    FUNCTION_ID = 629,             /* "FUNCTION-ID"  */
    FUNCTION_NAME = 630,           /* "intrinsic function name"  */
    FUNCTION_POINTER = 631,        /* "FUNCTION-POINTER"  */
    GENERATE = 632,                /* GENERATE  */
    GIVING = 633,                  /* GIVING  */
    GLOBAL = 634,                  /* GLOBAL  */
    GO = 635,                      /* GO  */
    GO_BACK = 636,                 /* "GO-BACK"  */
    GO_FORWARD = 637,              /* "GO-FORWARD"  */
    GO_HOME = 638,                 /* "GO-HOME"  */
    GO_SEARCH = 639,               /* "GO-SEARCH"  */
    GOBACK = 640,                  /* GOBACK  */
    GRAPHICAL = 641,               /* GRAPHICAL  */
    GREATER = 642,                 /* GREATER  */
    GREATER_OR_EQUAL = 643,        /* "GREATER OR EQUAL"  */
    GRID = 644,                    /* GRID  */
    GROUP = 645,                   /* GROUP  */
    GROUP_VALUE = 646,             /* "GROUP-VALUE"  */
    HANDLE = 647,                  /* HANDLE  */
    HAS_CHILDREN = 648,            /* "HAS-CHILDREN"  */
    HEADING = 649,                 /* HEADING  */
    HEADING_COLOR = 650,           /* "HEADING-COLOR"  */
    HEADING_DIVIDER_COLOR = 651,   /* "HEADING-DIVIDER-COLOR"  */
    HEADING_FONT = 652,            /* "HEADING-FONT"  */
    HEAVY = 653,                   /* HEAVY  */
    HEIGHT_IN_CELLS = 654,         /* "HEIGHT-IN-CELLS"  */
    HIDDEN_DATA = 655,             /* "HIDDEN-DATA"  */
    HIGHLIGHT = 656,               /* HIGHLIGHT  */
    HIGH_COLOR = 657,              /* "HIGH-COLOR"  */
    HIGH_VALUE = 658,              /* "HIGH-VALUE"  */
    HOT_TRACK = 659,               /* "HOT-TRACK"  */
    HSCROLL = 660,                 /* HSCROLL  */
    HSCROLL_POS = 661,             /* "HSCROLL-POS"  */
    ICON = 662,                    /* ICON  */
    ID = 663,                      /* ID  */
    IDENTIFIED = 664,              /* IDENTIFIED  */
    IDENTIFICATION = 665,          /* IDENTIFICATION  */
    IF = 666,                      /* IF  */
    IGNORE = 667,                  /* IGNORE  */
    IGNORING = 668,                /* IGNORING  */
    IN = 669,                      /* IN  */
    INDEPENDENT = 670,             /* INDEPENDENT  */
    INDEX = 671,                   /* INDEX  */
    INDEXED = 672,                 /* INDEXED  */
    INDICATE = 673,                /* INDICATE  */
    INITIALIZE = 674,              /* INITIALIZE  */
    INITIALIZED = 675,             /* INITIALIZED  */
    INITIATE = 676,                /* INITIATE  */
    INPUT = 677,                   /* INPUT  */
    INPUT_OUTPUT = 678,            /* "INPUT-OUTPUT"  */
    INQUIRE = 679,                 /* INQUIRE  */
    INSERTION_INDEX = 680,         /* "INSERTION-INDEX"  */
    INSERT_ROWS = 681,             /* "INSERT-ROWS"  */
    INSPECT = 682,                 /* INSPECT  */
    INSTALLATION = 683,            /* INSTALLATION  */
    INTERMEDIATE = 684,            /* INTERMEDIATE  */
    INTO = 685,                    /* INTO  */
    INTRINSIC = 686,               /* INTRINSIC  */
    INVALID = 687,                 /* INVALID  */
    INVALID_KEY = 688,             /* "INVALID KEY"  */
    IS = 689,                      /* IS  */
    ITEM = 690,                    /* ITEM  */
    ITEM_TEXT = 691,               /* "ITEM-TEXT"  */
    ITEM_TO_ADD = 692,             /* "ITEM-TO_ADD"  */
    ITEM_TO_DELETE = 693,          /* "ITEM-TO_DELETE"  */
    ITEM_TO_EMPTY = 694,           /* "ITEM-TO_EMPTY"  */
    ITEM_VALUE = 695,              /* "ITEM-VALUE"  */
    I_O = 696,                     /* "I-O"  */
    I_O_CONTROL = 697,             /* "I-O-CONTROL"  */
    JSON = 698,                    /* JSON  */
    JUSTIFIED = 699,               /* JUSTIFIED  */
    KEPT = 700,                    /* KEPT  */
    KEY = 701,                     /* KEY  */
    KEYBOARD = 702,                /* KEYBOARD  */
    LABEL = 703,                   /* LABEL  */
    LABEL_OFFSET = 704,            /* "LABEL-OFFSET"  */
    LARGE_FONT = 705,              /* "LARGE-FONT"  */
    LARGE_OFFSET = 706,            /* "LARGE-OFFSET"  */
    LAST = 707,                    /* LAST  */
    LAST_ROW = 708,                /* "LAST-ROW"  */
    LAYOUT_DATA = 709,             /* "LAYOUT-DATA"  */
    LAYOUT_MANAGER = 710,          /* "LAYOUT-MANAGER"  */
    LEADING = 711,                 /* LEADING  */
    LEADING_SHIFT = 712,           /* "LEADING-SHIFT"  */
    LEAVE = 713,                   /* LEAVE  */
    LEFT = 714,                    /* LEFT  */
    LEFTLINE = 715,                /* LEFTLINE  */
    LEFT_TEXT = 716,               /* "LEFT-TEXT"  */
    LENGTH = 717,                  /* LENGTH  */
    LENGTH_OF = 718,               /* "LENGTH OF"  */
    LENGTH_FUNC = 719,             /* "FUNCTION LENGTH/BYTE-LENGTH"  */
    LESS = 720,                    /* LESS  */
    LESS_OR_EQUAL = 721,           /* "LESS OR EQUAL"  */
    LEVEL_NUMBER = 722,            /* "level-number"  */
    LIKE = 723,                    /* LIKE  */
    LIMIT = 724,                   /* LIMIT  */
    LIMITS = 725,                  /* LIMITS  */
    LINAGE = 726,                  /* LINAGE  */
    LINAGE_COUNTER = 727,          /* "LINAGE-COUNTER"  */
    LINE = 728,                    /* LINE  */
    LINE_COUNTER = 729,            /* "LINE-COUNTER"  */
    LINE_LIMIT = 730,              /* "LINE LIMIT"  */
    LINE_SEQUENTIAL = 731,         /* "LINE-SEQUENTIAL"  */
    LINES = 732,                   /* LINES  */
    LINES_AT_ROOT = 733,           /* "LINES-AT-ROOT"  */
    LINKAGE = 734,                 /* LINKAGE  */
    LIST_BOX = 735,                /* "LIST-BOX"  */
    LITERAL = 736,                 /* "Literal"  */
    LM_RESIZE = 737,               /* "LM-RESIZE"  */
    LOC = 738,                     /* LOC  */
    LOCALE = 739,                  /* LOCALE  */
    LOCALE_DATE_FUNC = 740,        /* "FUNCTION LOCALE-DATE"  */
    LOCALE_TIME_FUNC = 741,        /* "FUNCTION LOCALE-TIME"  */
    LOCALE_TIME_FROM_FUNC = 742,   /* "FUNCTION LOCALE-TIME-FROM-SECONDS"  */
    LOCAL_STORAGE = 743,           /* "LOCAL-STORAGE"  */
    LOCK = 744,                    /* LOCK  */
    LOCK_HOLDING = 745,            /* "LOCK-HOLDING"  */
    LONG_DATE = 746,               /* "LONG-DATE"  */
    LOWER = 747,                   /* LOWER  */
    LOWERED = 748,                 /* LOWERED  */
    LOWER_CASE_FUNC = 749,         /* "FUNCTION LOWER-CASE"  */
    LOWLIGHT = 750,                /* LOWLIGHT  */
    LOW_COLOR = 751,               /* "LOW-COLOR"  */
    LOW_VALUE = 752,               /* "LOW-VALUE"  */
    MAGNETIC_TAPE = 753,           /* "MAGNETIC-TAPE"  */
    MANUAL = 754,                  /* MANUAL  */
    MASS_UPDATE = 755,             /* "MASS-UPDATE"  */
    MASTER_INDEX = 756,            /* "MASTER-INDEX"  */
    MAX_LINES = 757,               /* "MAX-LINES"  */
    MAX_PROGRESS = 758,            /* "MAX-PROGRESS"  */
    MAX_TEXT = 759,                /* "MAX-TEXT"  */
    MAX_VAL = 760,                 /* "MAX-VAL"  */
    MEMORY = 761,                  /* MEMORY  */
    MEDIUM_FONT = 762,             /* "MEDIUM-FONT"  */
    MENU = 763,                    /* MENU  */
    MERGE = 764,                   /* MERGE  */
    MESSAGE = 765,                 /* MESSAGE  */
    MICROSECOND_TIME = 766,        /* "MICROSECOND-TIME"  */
    MINUS = 767,                   /* MINUS  */
    MIN_VAL = 768,                 /* "MIN-VAL"  */
    MNEMONIC_NAME = 769,           /* "Mnemonic name"  */
    MODAL = 770,                   /* MODAL  */
    MODE = 771,                    /* MODE  */
    MODELESS = 772,                /* MODELESS  */
    MODIFY = 773,                  /* MODIFY  */
    MODULES = 774,                 /* MODULES  */
    MOVE = 775,                    /* MOVE  */
    MULTILINE = 776,               /* MULTILINE  */
    MULTIPLE = 777,                /* MULTIPLE  */
    MULTIPLY = 778,                /* MULTIPLY  */
    NAME = 779,                    /* NAME  */
    NAMED = 780,                   /* NAMED  */
    NAMESPACE = 781,               /* NAMESPACE  */
    NAMESPACE_PREFIX = 782,        /* "NAMESPACE-PREFIX"  */
    NATIONAL = 783,                /* NATIONAL  */
    NATIONAL_EDITED = 784,         /* "NATIONAL-EDITED"  */
    NATIONAL_OF_FUNC = 785,        /* "FUNCTION NATIONAL-OF"  */
    NATIVE = 786,                  /* NATIVE  */
    NAVIGATE_URL = 787,            /* "NAVIGATE-URL"  */
    NEAREST_AWAY_FROM_ZERO = 788,  /* "NEAREST-AWAY-FROM-ZERO"  */
    NEAREST_EVEN = 789,            /* "NEAREST-EVEN"  */
    NEAREST_TOWARD_ZERO = 790,     /* "NEAREST-TOWARD-ZERO"  */
    NEGATIVE = 791,                /* NEGATIVE  */
    NESTED = 792,                  /* NESTED  */
    NEW = 793,                     /* NEW  */
    NEXT = 794,                    /* NEXT  */
    NEXT_ITEM = 795,               /* "NEXT-ITEM"  */
    NEXT_GROUP = 796,              /* "NEXT GROUP"  */
    NEXT_PAGE = 797,               /* "NEXT PAGE"  */
    NO = 798,                      /* NO  */
    NO_ADVANCING = 799,            /* "NO ADVANCING"  */
    NO_AUTOSEL = 800,              /* "NO-AUTOSEL"  */
    NO_AUTO_DEFAULT = 801,         /* "NO-AUTO-DEFAULT"  */
    NO_BOX = 802,                  /* "NO-BOX"  */
    NO_DATA = 803,                 /* "NO DATA"  */
    NO_DIVIDERS = 804,             /* "NO-DIVIDERS"  */
    NO_ECHO = 805,                 /* "NO-ECHO"  */
    NO_F4 = 806,                   /* "NO-F4"  */
    NO_FOCUS = 807,                /* "NO-FOCUS"  */
    NO_GROUP_TAB = 808,            /* "NO-GROUP-TAB"  */
    NO_KEY_LETTER = 809,           /* "NO-KEY-LETTER"  */
    NO_SEARCH = 810,               /* "NO-SEARCH"  */
    NO_UPDOWN = 811,               /* "NO-UPDOWN"  */
    NOMINAL = 812,                 /* NOMINAL  */
    NONE = 813,                    /* NONE  */
    NONNUMERIC = 814,              /* NONNUMERIC  */
    NORMAL = 815,                  /* NORMAL  */
    NOT = 816,                     /* NOT  */
    NOTAB = 817,                   /* NOTAB  */
    NOTHING = 818,                 /* NOTHING  */
    NOTIFY = 819,                  /* NOTIFY  */
    NOTIFY_CHANGE = 820,           /* "NOTIFY-CHANGE"  */
    NOTIFY_DBLCLICK = 821,         /* "NOTIFY-DBLCLICK"  */
    NOTIFY_SELCHANGE = 822,        /* "NOTIFY-SELCHANGE"  */
    NOT_AT_END = 823,              /* "NOT AT END"  */
    NOT_EOP = 824,                 /* "NOT AT EOP"  */
    NOT_ON_ESCAPE = 825,           /* "NOT ON ESCAPE"  */
    NOT_EQUAL = 826,               /* "NOT EQUAL"  */
    NOT_ON_EXCEPTION = 827,        /* "NOT ON EXCEPTION"  */
    NOT_INVALID_KEY = 828,         /* "NOT INVALID KEY"  */
    NOT_ON_OVERFLOW = 829,         /* "NOT ON OVERFLOW"  */
    NOT_SIZE_ERROR = 830,          /* "NOT SIZE ERROR"  */
    NUM_COL_HEADINGS = 831,        /* "NUM-COL-HEADINGS"  */
    NUM_ROWS = 832,                /* "NUM-ROWS"  */
    NUMBER = 833,                  /* NUMBER  */
    NUMBERS = 834,                 /* NUMBERS  */
    NUMERIC = 835,                 /* NUMERIC  */
    NUMERIC_EDITED = 836,          /* "NUMERIC-EDITED"  */
    NUMVALC_FUNC = 837,            /* "FUNCTION NUMVAL-C"  */
    OBJECT = 838,                  /* OBJECT  */
    OBJECT_COMPUTER = 839,         /* "OBJECT-COMPUTER"  */
    OCCURS = 840,                  /* OCCURS  */
    OF = 841,                      /* OF  */
    OFF = 842,                     /* OFF  */
    OK_BUTTON = 843,               /* "OK-BUTTON"  */
    OMITTED = 844,                 /* OMITTED  */
    ON = 845,                      /* ON  */
    ONLY = 846,                    /* ONLY  */
    ON_ESCAPE = 847,               /* "ON ESCAPE"  */
    ON_EXCEPTION = 848,            /* "ON EXCEPTION"  */
    OPEN = 849,                    /* OPEN  */
    OPTIONAL = 850,                /* OPTIONAL  */
    OPTIONS = 851,                 /* OPTIONS  */
    OR = 852,                      /* OR  */
    ORDER = 853,                   /* ORDER  */
    ORGANIZATION = 854,            /* ORGANIZATION  */
    OTHER = 855,                   /* OTHER  */
    OTHERS = 856,                  /* OTHERS  */
    OUTPUT = 857,                  /* OUTPUT  */
    OVERLAP_LEFT = 858,            /* "OVERLAP-LEFT"  */
    OVERLAP_TOP = 859,             /* "OVERLAP-TOP"  */
    OVERLINE = 860,                /* OVERLINE  */
    PACKED_DECIMAL = 861,          /* "PACKED-DECIMAL"  */
    PADDING = 862,                 /* PADDING  */
    PASCAL = 863,                  /* PASCAL  */
    PAGE = 864,                    /* PAGE  */
    PAGE_COUNTER = 865,            /* "PAGE-COUNTER"  */
    PAGE_SETUP = 866,              /* "PAGE-SETUP"  */
    PAGED = 867,                   /* PAGED  */
    PARAGRAPH = 868,               /* PARAGRAPH  */
    PARENT = 869,                  /* PARENT  */
    PARSE = 870,                   /* PARSE  */
    PASSWORD = 871,                /* PASSWORD  */
    PERFORM = 872,                 /* PERFORM  */
    PERMANENT = 873,               /* PERMANENT  */
    PH = 874,                      /* PH  */
    PF = 875,                      /* PF  */
    PHYSICAL = 876,                /* PHYSICAL  */
    PICTURE = 877,                 /* PICTURE  */
    PICTURE_SYMBOL = 878,          /* "PICTURE SYMBOL"  */
    PIXEL = 879,                   /* PIXEL  */
    PLACEMENT = 880,               /* PLACEMENT  */
    PLUS = 881,                    /* PLUS  */
    POINTER = 882,                 /* POINTER  */
    POP_UP = 883,                  /* "POP-UP"  */
    POS = 884,                     /* POS  */
    POSITION = 885,                /* POSITION  */
    POSITION_SHIFT = 886,          /* "POSITION-SHIFT"  */
    POSITIVE = 887,                /* POSITIVE  */
    PRESENT = 888,                 /* PRESENT  */
    PREVIOUS = 889,                /* PREVIOUS  */
    PRINT = 890,                   /* PRINT  */
    PRINT_CONTROL = 891,           /* "PRINT-CONTROL"  */
    PRINT_NO_PROMPT = 892,         /* "PRINT-NO-PROMPT"  */
    PRINT_PREVIEW = 893,           /* "PRINT-PREVIEW"  */
    PRINTER = 894,                 /* PRINTER  */
    PRINTER_1 = 895,               /* "PRINTER-1"  */
    PRINTING = 896,                /* PRINTING  */
    PRIORITY = 897,                /* PRIORITY  */
    PROCEDURE = 898,               /* PROCEDURE  */
    PROCEDURES = 899,              /* PROCEDURES  */
    PROCEED = 900,                 /* PROCEED  */
    PROCESSING = 901,              /* PROCESSING  */
    PROGRAM = 902,                 /* PROGRAM  */
    PROGRAM_ID = 903,              /* "PROGRAM-ID"  */
    PROGRAM_NAME = 904,            /* "program name"  */
    PROGRAM_POINTER = 905,         /* "PROGRAM-POINTER"  */
    PROGRESS = 906,                /* PROGRESS  */
    PROHIBITED = 907,              /* PROHIBITED  */
    PROMPT = 908,                  /* PROMPT  */
    PROPERTIES = 909,              /* PROPERTIES  */
    PROPERTY = 910,                /* PROPERTY  */
    PROTECTED = 911,               /* PROTECTED  */
    PROTOTYPE = 912,               /* PROTOTYPE  */
    PURGE = 913,                   /* PURGE  */
    PUSH_BUTTON = 914,             /* "PUSH-BUTTON"  */
    QUERY_INDEX = 915,             /* "QUERY-INDEX"  */
    QUEUE = 916,                   /* QUEUE  */
    QUOTE = 917,                   /* QUOTE  */
    RADIO_BUTTON = 918,            /* "RADIO-BUTTON"  */
    RAISE = 919,                   /* RAISE  */
    RAISED = 920,                  /* RAISED  */
    RAISING = 921,                 /* RAISING  */
    RANDOM = 922,                  /* RANDOM  */
    RD = 923,                      /* RD  */
    READ = 924,                    /* READ  */
    READERS = 925,                 /* READERS  */
    READ_ONLY = 926,               /* "READ-ONLY"  */
    READY = 927,                   /* READY  */
    RECEIVE = 928,                 /* RECEIVE  */
    RECEIVED = 929,                /* RECEIVED  */
    RECORD = 930,                  /* RECORD  */
    RECORD_DATA = 931,             /* "RECORD-DATA"  */
    RECORD_OVERFLOW = 932,         /* "RECORD-OVERFLOW"  */
    RECORD_TO_ADD = 933,           /* "RECORD-TO-ADD"  */
    RECORD_TO_DELETE = 934,        /* "RECORD-TO-DELETE"  */
    RECORDING = 935,               /* RECORDING  */
    RECORDS = 936,                 /* RECORDS  */
    RECURSIVE = 937,               /* RECURSIVE  */
    REDEFINES = 938,               /* REDEFINES  */
    REEL = 939,                    /* REEL  */
    REFERENCE = 940,               /* REFERENCE  */
    REFERENCES = 941,              /* REFERENCES  */
    REFRESH = 942,                 /* REFRESH  */
    REGION_COLOR = 943,            /* "REGION-COLOR"  */
    RELATION = 944,                /* RELATION  */
    RELATIVE = 945,                /* RELATIVE  */
    RELEASE = 946,                 /* RELEASE  */
    REMAINDER = 947,               /* REMAINDER  */
    REMARKS = 948,                 /* REMARKS  */
    REMOVAL = 949,                 /* REMOVAL  */
    RENAMES = 950,                 /* RENAMES  */
    REORG_CRITERIA = 951,          /* "REORG-CRITERIA"  */
    REPEATED = 952,                /* REPEATED  */
    REPLACE = 953,                 /* REPLACE  */
    REPLACING = 954,               /* REPLACING  */
    REPORT = 955,                  /* REPORT  */
    REPORTING = 956,               /* REPORTING  */
    REPORTS = 957,                 /* REPORTS  */
    REPOSITORY = 958,              /* REPOSITORY  */
    REQUIRED = 959,                /* REQUIRED  */
    REREAD = 960,                  /* REREAD  */
    RERUN = 961,                   /* RERUN  */
    RESERVE = 962,                 /* RESERVE  */
    RESET = 963,                   /* RESET  */
    RESET_GRID = 964,              /* "RESET-GRID"  */
    RESET_LIST = 965,              /* "RESET-LIST"  */
    RESET_TABS = 966,              /* "RESET-TABS"  */
    RETRY = 967,                   /* RETRY  */
    RETURN = 968,                  /* RETURN  */
    RETURNING = 969,               /* RETURNING  */
    REVERSE = 970,                 /* REVERSE  */
    REVERSE_FUNC = 971,            /* "FUNCTION REVERSE"  */
    REVERSE_VIDEO = 972,           /* "REVERSE-VIDEO"  */
    REVERSED = 973,                /* REVERSED  */
    REWIND = 974,                  /* REWIND  */
    REWRITE = 975,                 /* REWRITE  */
    RF = 976,                      /* RF  */
    RH = 977,                      /* RH  */
    RIGHT = 978,                   /* RIGHT  */
    RIGHT_ALIGN = 979,             /* "RIGHT-ALIGN"  */
    RIGHTLINE = 980,               /* RIGHTLINE  */
    RIMMED = 981,                  /* RIMMED  */
    ROLLBACK = 982,                /* ROLLBACK  */
    ROUNDED = 983,                 /* ROUNDED  */
    ROUNDING = 984,                /* ROUNDING  */
    ROW_COLOR = 985,               /* "ROW-COLOR"  */
    ROW_COLOR_PATTERN = 986,       /* "ROW-COLOR-PATTERN"  */
    ROW_DIVIDERS = 987,            /* "ROW-DIVIDERS"  */
    ROW_FONT = 988,                /* "ROW-FONT"  */
    ROW_HEADINGS = 989,            /* "ROW-HEADINGS"  */
    ROW_PROTECTION = 990,          /* "ROW-PROTECTION"  */
    RUN = 991,                     /* RUN  */
    S = 992,                       /* S  */
    SAME = 993,                    /* SAME  */
    SAVE_AS = 994,                 /* "SAVE-AS"  */
    SAVE_AS_NO_PROMPT = 995,       /* "SAVE-AS-NO-PROMPT"  */
    SCREEN = 996,                  /* SCREEN  */
    SCREEN_CONTROL = 997,          /* "SCREEN CONTROL"  */
    SCROLL = 998,                  /* SCROLL  */
    SCROLL_BAR = 999,              /* "SCROLL-BAR"  */
    SD = 1000,                     /* SD  */
    SEARCH = 1001,                 /* SEARCH  */
    SEARCH_OPTIONS = 1002,         /* "SEARCH-OPTIONS"  */
    SEARCH_TEXT = 1003,            /* "SEARCH-TEXT"  */
    SECONDS = 1004,                /* SECONDS  */
    SECTION = 1005,                /* SECTION  */
    SECURE = 1006,                 /* SECURE  */
    SECURITY = 1007,               /* SECURITY  */
    SEGMENT = 1008,                /* SEGMENT  */
    SEGMENT_LIMIT = 1009,          /* "SEGMENT-LIMIT"  */
    SELECT = 1010,                 /* SELECT  */
    SELECTION_INDEX = 1011,        /* "SELECTION-INDEX"  */
    SELECTION_TEXT = 1012,         /* "SELECTION-TEXT"  */
    SELECT_ALL = 1013,             /* "SELECTION-ALL"  */
    SELF_ACT = 1014,               /* "SELF-ACT"  */
    SEMI_COLON = 1015,             /* "semi-colon"  */
    SEND = 1016,                   /* SEND  */
    SENTENCE = 1017,               /* SENTENCE  */
    SEPARATE = 1018,               /* SEPARATE  */
    SEPARATION = 1019,             /* SEPARATION  */
    SEQUENCE = 1020,               /* SEQUENCE  */
    SEQUENTIAL = 1021,             /* SEQUENTIAL  */
    SET = 1022,                    /* SET  */
    SEVENTY_EIGHT = 1023,          /* "level-number 78"  */
    SHADING = 1024,                /* SHADING  */
    SHADOW = 1025,                 /* SHADOW  */
    SHARING = 1026,                /* SHARING  */
    SHORT_DATE = 1027,             /* "SHORT-DATE"  */
    SHOW_LINES = 1028,             /* "SHOW-LINES"  */
    SHOW_NONE = 1029,              /* "SHOW-NONE"  */
    SHOW_SEL_ALWAYS = 1030,        /* "SHOW-SEL-ALWAYS"  */
    SIGN = 1031,                   /* SIGN  */
    SIGNED = 1032,                 /* SIGNED  */
    SIGNED_INT = 1033,             /* "SIGNED-INT"  */
    SIGNED_LONG = 1034,            /* "SIGNED-LONG"  */
    SIGNED_SHORT = 1035,           /* "SIGNED-SHORT"  */
    SIXTY_SIX = 1036,              /* "level-number 66"  */
    SIZE = 1037,                   /* SIZE  */
    SIZE_ERROR = 1038,             /* "SIZE ERROR"  */
    SMALL_FONT = 1039,             /* "SMALL-FONT"  */
    SORT = 1040,                   /* SORT  */
    SORT_MERGE = 1041,             /* "SORT-MERGE"  */
    SORT_ORDER = 1042,             /* "SORT-ORDER"  */
    SOURCE = 1043,                 /* SOURCE  */
    SOURCE_COMPUTER = 1044,        /* "SOURCE-COMPUTER"  */
    SPACE = 1045,                  /* SPACE  */
    SPECIAL_NAMES = 1046,          /* "SPECIAL-NAMES"  */
    SPINNER = 1047,                /* SPINNER  */
    SQUARE = 1048,                 /* SQUARE  */
    STANDARD = 1049,               /* STANDARD  */
    STANDARD_1 = 1050,             /* "STANDARD-1"  */
    STANDARD_2 = 1051,             /* "STANDARD-2"  */
    STANDARD_BINARY = 1052,        /* "STANDARD-BINARY"  */
    STANDARD_DECIMAL = 1053,       /* "STANDARD-DECIMAL"  */
    START = 1054,                  /* START  */
    START_X = 1055,                /* "START-X"  */
    START_Y = 1056,                /* "START-Y"  */
    STATIC = 1057,                 /* STATIC  */
    STATIC_LIST = 1058,            /* "STATIC-LIST"  */
    STATUS = 1059,                 /* STATUS  */
    STATUS_BAR = 1060,             /* "STATUS-BAR"  */
    STATUS_TEXT = 1061,            /* "STATUS-TEXT"  */
    STDCALL = 1062,                /* STDCALL  */
    STEP = 1063,                   /* STEP  */
    STOP = 1064,                   /* STOP  */
    STRING = 1065,                 /* STRING  */
    STRONG = 1066,                 /* STRONG  */
    STYLE = 1067,                  /* STYLE  */
    SUB_QUEUE_1 = 1068,            /* "SUB-QUEUE-1"  */
    SUB_QUEUE_2 = 1069,            /* "SUB-QUEUE-2"  */
    SUB_QUEUE_3 = 1070,            /* "SUB-QUEUE-3"  */
    SUBSTITUTE_FUNC = 1071,        /* "FUNCTION SUBSTITUTE"  */
    SUBSTITUTE_CASE_FUNC = 1072,   /* "FUNCTION SUBSTITUTE-CASE"  */
    SUBTRACT = 1073,               /* SUBTRACT  */
    SUBWINDOW = 1074,              /* SUBWINDOW  */
    SUM = 1075,                    /* SUM  */
    SUPPRESS = 1076,               /* SUPPRESS  */
    SUPPRESS_XML = 1077,           /* "SUPPRESS"  */
    SYMBOL = 1078,                 /* SYMBOL  */
    SYMBOLIC = 1079,               /* SYMBOLIC  */
    SYNCHRONIZED = 1080,           /* SYNCHRONIZED  */
    SYSTEM_DEFAULT = 1081,         /* "SYSTEM-DEFAULT"  */
    SYSTEM_INFO = 1082,            /* "SYSTEM-INFO"  */
    SYSTEM_OFFSET = 1083,          /* "SYSTEM-OFFSET"  */
    TAB = 1084,                    /* TAB  */
    TAB_TO_ADD = 1085,             /* "TAB-TO-ADD"  */
    TAB_TO_DELETE = 1086,          /* "TAB-TO-DELETE"  */
    TABLE = 1087,                  /* TABLE  */
    TALLYING = 1088,               /* TALLYING  */
    TEMPORARY = 1089,              /* TEMPORARY  */
    TAPE = 1090,                   /* TAPE  */
    TERMINAL = 1091,               /* TERMINAL  */
    TERMINATE = 1092,              /* TERMINATE  */
    TERMINAL_INFO = 1093,          /* "TERMINAL-INFO"  */
    TERMINATION_VALUE = 1094,      /* "TERMINATION-VALUE"  */
    TEST = 1095,                   /* TEST  */
    TEXT = 1096,                   /* TEXT  */
    THAN = 1097,                   /* THAN  */
    THEN = 1098,                   /* THEN  */
    THREAD = 1099,                 /* THREAD  */
    THREADS = 1100,                /* THREADS  */
    THRU = 1101,                   /* THRU  */
    THUMB_POSITION = 1102,         /* "THUMB-POSITION"  */
    TILED_HEADINGS = 1103,         /* "TILED-HEADINGS"  */
    TIME = 1104,                   /* TIME  */
    TIME_OUT = 1105,               /* "TIME-OUT"  */
    TIMES = 1106,                  /* TIMES  */
    TITLE = 1107,                  /* TITLE  */
    TITLE_POSITION = 1108,         /* "TITLE-POSITION"  */
    TO = 1109,                     /* TO  */
    TOK_AMPER = 1110,              /* "&"  */
    TOK_CLOSE_PAREN = 1111,        /* ")"  */
    TOK_COLON = 1112,              /* ":"  */
    TOK_DIV = 1113,                /* "/"  */
    TOK_DOT = 1114,                /* "."  */
    TOK_EQUAL = 1115,              /* "="  */
    TOK_EXTERN = 1116,             /* "EXTERN"  */
    TOK_FALSE = 1117,              /* "FALSE"  */
    TOK_FILE = 1118,               /* "FILE"  */
    TOK_GREATER = 1119,            /* ">"  */
    TOK_INITIAL = 1120,            /* "INITIAL"  */
    TOK_LESS = 1121,               /* "<"  */
    TOK_MINUS = 1122,              /* "-"  */
    TOK_MUL = 1123,                /* "*"  */
    TOK_NULL = 1124,               /* "NULL"  */
    TOK_OVERFLOW = 1125,           /* "OVERFLOW"  */
    TOK_OPEN_PAREN = 1126,         /* "("  */
    TOK_PLUS = 1127,               /* "+"  */
    TOK_TRUE = 1128,               /* "TRUE"  */
    TOP = 1129,                    /* TOP  */
    TOWARD_GREATER = 1130,         /* "TOWARD-GREATER"  */
    TOWARD_LESSER = 1131,          /* "TOWARD-LESSER"  */
    TRACE = 1132,                  /* TRACE  */
    TRACK = 1133,                  /* TRACK  */
    TRACKS = 1134,                 /* TRACKS  */
    TRACK_AREA = 1135,             /* "TRACK-AREA"  */
    TRACK_LIMIT = 1136,            /* "TRACK-LIMIT"  */
    TRADITIONAL_FONT = 1137,       /* "TRADITIONAL-FONT"  */
    TRAILING = 1138,               /* TRAILING  */
    TRAILING_SHIFT = 1139,         /* "TRAILING-SHIFT"  */
    TRANSFORM = 1140,              /* TRANSFORM  */
    TRANSPARENT = 1141,            /* TRANSPARENT  */
    TREE_VIEW = 1142,              /* "TREE-VIEW"  */
    TRIM_FUNC = 1143,              /* "FUNCTION TRIM"  */
    TRUNCATION = 1144,             /* TRUNCATION  */
    TYPE = 1145,                   /* TYPE  */
    TYPEDEF = 1146,                /* TYPEDEF  */
    U = 1147,                      /* U  */
    UCS_4 = 1148,                  /* "UCS-4"  */
    UNBOUNDED = 1149,              /* UNBOUNDED  */
    UNDERLINE = 1150,              /* UNDERLINE  */
    UNFRAMED = 1151,               /* UNFRAMED  */
    UNIT = 1152,                   /* UNIT  */
    UNLOCK = 1153,                 /* UNLOCK  */
    UNSIGNED = 1154,               /* UNSIGNED  */
    UNSIGNED_INT = 1155,           /* "UNSIGNED-INT"  */
    UNSIGNED_LONG = 1156,          /* "UNSIGNED-LONG"  */
    UNSIGNED_SHORT = 1157,         /* "UNSIGNED-SHORT"  */
    UNSORTED = 1158,               /* UNSORTED  */
    UNSTRING = 1159,               /* UNSTRING  */
    UNTIL = 1160,                  /* UNTIL  */
    UP = 1161,                     /* UP  */
    UPDATE = 1162,                 /* UPDATE  */
    UPDATERS = 1163,               /* UPDATERS  */
    UPON = 1164,                   /* UPON  */
    UPON_ARGUMENT_NUMBER = 1165,   /* "UPON ARGUMENT-NUMBER"  */
    UPON_COMMAND_LINE = 1166,      /* "UPON COMMAND-LINE"  */
    UPON_ENVIRONMENT_NAME = 1167,  /* "UPON ENVIRONMENT-NAME"  */
    UPON_ENVIRONMENT_VALUE = 1168, /* "UPON ENVIRONMENT-VALUE"  */
    UPPER = 1169,                  /* UPPER  */
    UPPER_CASE_FUNC = 1170,        /* "FUNCTION UPPER-CASE"  */
    USAGE = 1171,                  /* USAGE  */
    USE = 1172,                    /* USE  */
    USE_ALT = 1173,                /* "USE-ALT"  */
    USE_RETURN = 1174,             /* "USE-RETURN"  */
    USE_TAB = 1175,                /* "USE-TAB"  */
    USER = 1176,                   /* USER  */
    USER_DEFAULT = 1177,           /* "USER-DEFAULT"  */
    USER_FUNCTION_NAME = 1178,     /* "user function name"  */
    USING = 1179,                  /* USING  */
    UTF_8 = 1180,                  /* "UTF-8"  */
    UTF_16 = 1181,                 /* "UTF-16"  */
    V = 1182,                      /* V  */
    VALID = 1183,                  /* VALID  */
    VALIDATE = 1184,               /* VALIDATE  */
    VALIDATE_STATUS = 1185,        /* "VALIDATE-STATUS"  */
    VALIDATING = 1186,             /* VALIDATING  */
    VALUE = 1187,                  /* VALUE  */
    VALUE_FORMAT = 1188,           /* "VALUE-FORMAT"  */
    VALUES = 1189,                 /* VALUES  */
    VARIABLE = 1190,               /* VARIABLE  */
    VARIANT = 1191,                /* VARIANT  */
    VARYING = 1192,                /* VARYING  */
    VERTICAL = 1193,               /* VERTICAL  */
    VERY_HEAVY = 1194,             /* "VERY-HEAVY"  */
    VIRTUAL_WIDTH = 1195,          /* "VIRTUAL-WIDTH"  */
    VOLATILE = 1196,               /* VOLATILE  */
    VPADDING = 1197,               /* VPADDING  */
    VSCROLL = 1198,                /* VSCROLL  */
    VSCROLL_BAR = 1199,            /* "VSCROLL-BAR"  */
    VSCROLL_POS = 1200,            /* "VSCROLL-POS"  */
    VTOP = 1201,                   /* VTOP  */
    WAIT = 1202,                   /* WAIT  */
    WEB_BROWSER = 1203,            /* "WEB-BROWSER"  */
    WHEN = 1204,                   /* WHEN  */
    WHEN_COMPILED_FUNC = 1205,     /* "FUNCTION WHEN-COMPILED"  */
    WHEN_XML = 1206,               /* "WHEN"  */
    WIDTH = 1207,                  /* WIDTH  */
    WIDTH_IN_CELLS = 1208,         /* "WIDTH-IN-CELLS"  */
    WINAPI = 1209,                 /* WINAPI  */
    WINDOW = 1210,                 /* WINDOW  */
    WITH = 1211,                   /* WITH  */
    WORD = 1212,                   /* "Identifier"  */
    WORDS = 1213,                  /* WORDS  */
    WORKING_STORAGE = 1214,        /* "WORKING-STORAGE"  */
    WRAP = 1215,                   /* WRAP  */
    WRITE = 1216,                  /* WRITE  */
    WRITE_ONLY = 1217,             /* "WRITE-ONLY"  */
    WRITE_VERIFY = 1218,           /* "WRITE-VERIFY"  */
    WRITERS = 1219,                /* WRITERS  */
    X = 1220,                      /* X  */
    XML = 1221,                    /* XML  */
    XML_DECLARATION = 1222,        /* "XML-DECLARATION"  */
    XML_SCHEMA = 1223,             /* "XML-SCHEMA"  */
    Y = 1224,                      /* Y  */
    YYYYDDD = 1225,                /* YYYYDDD  */
    YYYYMMDD = 1226,               /* YYYYMMDD  */
    ZERO = 1227,                   /* ZERO  */
    LEVEL_NUMBER_IN_AREA_A = 1228, /* "level-number (Area A)"  */
    WORD_IN_AREA_A = 1229,         /* "Identifier (Area A)"  */
    SHIFT_PREFER = 1230            /* SHIFT_PREFER  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef int YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;


int yyparse (void);


#endif /* !YY_YY_PARSER_H_INCLUDED  */
